import pytest
import sys

sys.path.append('src')

from backend.app.routers.schedule_router import *
from backend.app.routers.types import TeamID, RescheduleRequest
from backend.app.db.queries import delete_reschedule_request

@pytest.mark.asyncio
async def test_get_scheduled_games():
    response = await get_scheduled_games()
    games = [
        {'id': 1, 'date': '2025-05-10', 'time': '2', 'field': '3', 'home_team_score': 4, 'away_team_score': 6, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 2, 'date': '2025-06-26', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 3, 'date': '2025-07-02', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 4, 'date': '2025-06-13', 'time': '2', 'field': '3', 'home_team_score': 7, 'away_team_score': 4, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 5, 'date': '2025-07-22', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 6, 'date': '2025-07-01', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 7, 'date': '2025-05-23', 'time': '1', 'field': '1', 'home_team_score': 8, 'away_team_score': 4, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 8, 'date': '2025-06-05', 'time': '2', 'field': '1', 'home_team_score': 3, 'away_team_score': 7, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 9, 'date': '2025-05-28', 'time': '2', 'field': '2', 'home_team_score': 3, 'away_team_score': 5, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 10, 'date': '2025-08-09', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 11, 'date': '2025-08-01', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 12, 'date': '2025-07-30', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 13, 'date': '2025-08-06', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 14, 'date': '2025-05-14', 'time': '1', 'field': '3', 'home_team_score': 8, 'away_team_score': 4, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 15, 'date': '2025-07-18', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 16, 'date': '2025-08-15', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 17, 'date': '2025-05-14', 'time': '1', 'field': '2', 'home_team_score': 6, 'away_team_score': 8, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 18, 'date': '2025-05-24', 'time': '1', 'field': '2', 'home_team_score': 4, 'away_team_score': 7, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 19, 'date': '2025-07-02', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 20, 'date': '2025-05-31', 'time': '3', 'field': '3', 'home_team_score': 3, 'away_team_score': 4, 'played': True, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 21, 'date': '2025-05-17', 'time': '3', 'field': '2', 'home_team_score': 6, 'away_team_score': 6, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 22, 'date': '2025-06-25', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 23, 'date': '2025-05-20', 'time': '2', 'field': '2', 'home_team_score': 5, 'away_team_score': 5, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 24, 'date': '2025-07-05', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 25, 'date': '2025-05-21', 'time': '1', 'field': '2', 'home_team_score': 8, 'away_team_score': 4, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 26, 'date': '2025-07-12', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 27, 'date': '2025-08-12', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 28, 'date': '2025-05-31', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 1, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 29, 'date': '2025-05-28', 'time': '1', 'field': '3', 'home_team_score': 4, 'away_team_score': 1, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 30, 'date': '2025-06-17', 'time': '2', 'field': '2', 'home_team_score': 3, 'away_team_score': 7, 'played': True, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 31, 'date': '2025-05-22', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 8, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 32, 'date': '2025-06-07', 'time': '1', 'field': '3', 'home_team_score': 5, 'away_team_score': 6, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 33, 'date': '2025-07-25', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 34, 'date': '2025-08-02', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 35, 'date': '2025-06-12', 'time': '3', 'field': '1', 'home_team_score': 7, 'away_team_score': 6, 'played': True, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 36, 'date': '2025-06-14', 'time': '1', 'field': '2', 'home_team_score': 7, 'away_team_score': 5, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 37, 'date': '2025-08-20', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 38, 'date': '2025-08-20', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 39, 'date': '2025-07-05', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 40, 'date': '2025-08-08', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 41, 'date': '2025-08-15', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 42, 'date': '2025-06-17', 'time': '2', 'field': '3', 'home_team_score': 8, 'away_team_score': 5, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 43, 'date': '2025-06-11', 'time': '2', 'field': '2', 'home_team_score': 7, 'away_team_score': 5, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 44, 'date': '2025-07-11', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 45, 'date': '2025-06-21', 'time': '1', 'field': '2', 'home_team_score': 5, 'away_team_score': 8, 'played': True, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 46, 'date': '2025-06-28', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 47, 'date': '2025-07-09', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 48, 'date': '2025-08-05', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 49, 'date': '2025-07-17', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 50, 'date': '2025-06-07', 'time': '3', 'field': '3', 'home_team_score': 3, 'away_team_score': 7, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 51, 'date': '2025-07-16', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 52, 'date': '2025-05-08', 'time': '1', 'field': '2', 'home_team_score': 6, 'away_team_score': 3, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 53, 'date': '2025-07-19', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 54, 'date': '2025-07-03', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 55, 'date': '2025-07-23', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 56, 'date': '2025-06-25', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 57, 'date': '2025-06-10', 'time': '2', 'field': '2', 'home_team_score': 2, 'away_team_score': 3, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 58, 'date': '2025-08-14', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 59, 'date': '2025-05-20', 'time': '2', 'field': '3', 'home_team_score': 2, 'away_team_score': 8, 'played': True, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 60, 'date': '2025-05-29', 'time': '1', 'field': '1', 'home_team_score': 7, 'away_team_score': 2, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 61, 'date': '2025-06-04', 'time': '2', 'field': '3', 'home_team_score': 4, 'away_team_score': 3, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 62, 'date': '2025-08-08', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 63, 'date': '2025-06-03', 'time': '2', 'field': '2', 'home_team_score': 3, 'away_team_score': 7, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 64, 'date': '2025-08-01', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 65, 'date': '2025-08-19', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 66, 'date': '2025-06-11', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 2, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 67, 'date': '2025-08-13', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 68, 'date': '2025-08-05', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 69, 'date': '2025-06-10', 'time': '2', 'field': '3', 'home_team_score': 7, 'away_team_score': 7, 'played': True, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 70, 'date': '2025-08-16', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 71, 'date': '2025-05-15', 'time': '1', 'field': '1', 'home_team_score': 5, 'away_team_score': 1, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 72, 'date': '2025-06-20', 'time': '3', 'field': '2', 'home_team_score': 7, 'away_team_score': 2, 'played': True, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 73, 'date': '2025-05-07', 'time': '1', 'field': '3', 'home_team_score': 5, 'away_team_score': 2, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 74, 'date': '2025-08-09', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 75, 'date': '2025-05-09', 'time': '1', 'field': '3', 'home_team_score': 2, 'away_team_score': 4, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 76, 'date': '2025-07-12', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 77, 'date': '2025-08-14', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 78, 'date': '2025-07-29', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 79, 'date': '2025-07-18', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 80, 'date': '2025-08-20', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 81, 'date': '2025-06-21', 'time': '2', 'field': '2', 'home_team_score': 7, 'away_team_score': 2, 'played': True, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 82, 'date': '2025-05-16', 'time': '2', 'field': '2', 'home_team_score': 7, 'away_team_score': 5, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 83, 'date': '2025-05-13', 'time': '1', 'field': '1', 'home_team_score': 4, 'away_team_score': 6, 'played': True, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 84, 'date': '2025-07-04', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 85, 'date': '2025-07-02', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 86, 'date': '2025-07-01', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 87, 'date': '2025-06-11', 'time': '3', 'field': '2', 'home_team_score': 8, 'away_team_score': 7, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 88, 'date': '2025-05-28', 'time': '2', 'field': '1', 'home_team_score': 6, 'away_team_score': 3, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 89, 'date': '2025-07-26', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 90, 'date': '2025-06-10', 'time': '1', 'field': '3', 'home_team_score': 3, 'away_team_score': 4, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 91, 'date': '2025-05-08', 'time': '3', 'field': '3', 'home_team_score': 8, 'away_team_score': 7, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 92, 'date': '2025-06-07', 'time': '2', 'field': '1', 'home_team_score': 6, 'away_team_score': 8, 'played': True, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 93, 'date': '2025-07-11', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 94, 'date': '2025-06-18', 'time': '2', 'field': '3', 'home_team_score': 2, 'away_team_score': 7, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 95, 'date': '2025-08-16', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 96, 'date': '2025-07-22', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 97, 'date': '2025-07-29', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 98, 'date': '2025-05-09', 'time': '2', 'field': '1', 'home_team_score': 8, 'away_team_score': 6, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 99, 'date': '2025-07-15', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 100, 'date': '2025-08-12', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 101, 'date': '2025-05-21', 'time': '2', 'field': '1', 'home_team_score': 7, 'away_team_score': 6, 'played': True, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 102, 'date': '2025-06-04', 'time': '3', 'field': '2', 'home_team_score': 6, 'away_team_score': 7, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 103, 'date': '2025-07-04', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 104, 'date': '2025-05-27', 'time': '1', 'field': '1', 'home_team_score': 6, 'away_team_score': 5, 'played': True, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 105, 'date': '2025-06-13', 'time': '3', 'field': '2', 'home_team_score': 2, 'away_team_score': 5, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 106, 'date': '2025-06-24', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 107, 'date': '2025-05-10', 'time': '2', 'field': '1', 'home_team_score': 7, 'away_team_score': 1, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 108, 'date': '2025-07-05', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 109, 'date': '2025-06-03', 'time': '3', 'field': '3', 'home_team_score': 7, 'away_team_score': 3, 'played': True, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 110, 'date': '2025-05-10', 'time': '1', 'field': '1', 'home_team_score': 4, 'away_team_score': 6, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 111, 'date': '2025-08-01', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 112, 'date': '2025-05-21', 'time': '1', 'field': '3', 'home_team_score': 6, 'away_team_score': 6, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 113, 'date': '2025-08-06', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 114, 'date': '2025-06-21', 'time': '2', 'field': '1', 'home_team_score': 1, 'away_team_score': 3, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 115, 'date': '2025-07-11', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 116, 'date': '2025-07-26', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 117, 'date': '2025-05-22', 'time': '1', 'field': '2', 'home_team_score': 6, 'away_team_score': 4, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 118, 'date': '2025-08-13', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 119, 'date': '2025-07-31', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 120, 'date': '2025-08-05', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 121, 'date': '2025-07-08', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 122, 'date': '2025-06-21', 'time': '3', 'field': '3', 'home_team_score': 5, 'away_team_score': 8, 'played': True, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 123, 'date': '2025-06-14', 'time': '1', 'field': '3', 'home_team_score': 8, 'away_team_score': 7, 'played': True, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 124, 'date': '2025-06-13', 'time': '2', 'field': '2', 'home_team_score': 8, 'away_team_score': 2, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 125, 'date': '2025-05-24', 'time': '3', 'field': '1', 'home_team_score': 3, 'away_team_score': 2, 'played': True, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 126, 'date': '2025-07-19', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 127, 'date': '2025-07-24', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 128, 'date': '2025-05-08', 'time': '1', 'field': '3', 'home_team_score': 2, 'away_team_score': 6, 'played': True, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 129, 'date': '2025-08-01', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 130, 'date': '2025-06-25', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 131, 'date': '2025-07-23', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 132, 'date': '2025-06-06', 'time': '2', 'field': '3', 'home_team_score': 2, 'away_team_score': 2, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 133, 'date': '2025-05-15', 'time': '1', 'field': '2', 'home_team_score': 7, 'away_team_score': 6, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 134, 'date': '2025-08-12', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 135, 'date': '2025-05-30', 'time': '1', 'field': '1', 'home_team_score': 5, 'away_team_score': 6, 'played': True, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 136, 'date': '2025-08-15', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 137, 'date': '2025-05-06', 'time': '3', 'field': '1', 'home_team_score': 3, 'away_team_score': 4, 'played': True, 'home_team_id': 11, 'home_team_name': 'Cubs', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 138, 'date': '2025-07-03', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 13, 'away_team_name': 'White Sox'}, 
        {'id': 139, 'date': '2025-06-25', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 140, 'date': '2025-05-17', 'time': '1', 'field': '2', 'home_team_score': 2, 'away_team_score': 7, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 141, 'date': '2025-08-02', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 142, 'date': '2025-05-07', 'time': '2', 'field': '2', 'home_team_score': 8, 'away_team_score': 7, 'played': True, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 143, 'date': '2025-05-06', 'time': '2', 'field': '3', 'home_team_score': 6, 'away_team_score': 8, 'played': True, 'home_team_id': 9, 'home_team_name': 'Rockies', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 144, 'date': '2025-05-14', 'time': '1', 'field': '1', 'home_team_score': 8, 'away_team_score': 2, 'played': True, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 145, 'date': '2025-05-29', 'time': '3', 'field': '3', 'home_team_score': 4, 'away_team_score': 7, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 8, 'away_team_name': 'Angels'}, 
        {'id': 146, 'date': '2025-06-07', 'time': '3', 'field': '1', 'home_team_score': 1, 'away_team_score': 6, 'played': True, 'home_team_id': 12, 'home_team_name': 'Padres', 'away_team_id': 14, 'away_team_name': 'Guardians'}, 
        {'id': 147, 'date': '2025-07-02', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 10, 'home_team_name': 'Royals', 'away_team_id': 9, 'away_team_name': 'Rockies'}, 
        {'id': 148, 'date': '2025-08-06', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 8, 'home_team_name': 'Angels', 'away_team_id': 12, 'away_team_name': 'Padres'}, 
        {'id': 149, 'date': '2025-05-15', 'time': '2', 'field': '3', 'home_team_score': 4, 'away_team_score': 6, 'played': True, 'home_team_id': 13, 'home_team_name': 'White Sox', 'away_team_id': 11, 'away_team_name': 'Cubs'}, 
        {'id': 150, 'date': '2025-08-09', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 14, 'home_team_name': 'Guardians', 'away_team_id': 10, 'away_team_name': 'Royals'}, 
        {'id': 151, 'date': '2025-08-01', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 152, 'date': '2025-08-13', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 153, 'date': '2025-07-24', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 154, 'date': '2025-07-19', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 155, 'date': '2025-05-22', 'time': '2', 'field': '2', 'home_team_score': 3, 'away_team_score': 6, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 156, 'date': '2025-06-19', 'time': '2', 'field': '2', 'home_team_score': 8, 'away_team_score': 2, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 157, 'date': '2025-07-04', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 158, 'date': '2025-05-15', 'time': '3', 'field': '2', 'home_team_score': 3, 'away_team_score': 4, 'played': True, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 159, 'date': '2025-07-04', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 160, 'date': '2025-07-01', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 161, 'date': '2025-08-06', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 162, 'date': '2025-06-26', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 163, 'date': '2025-05-24', 'time': '2', 'field': '1', 'home_team_score': 1, 'away_team_score': 5, 'played': True, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 164, 'date': '2025-06-10', 'time': '1', 'field': '2', 'home_team_score': 1, 'away_team_score': 2, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 165, 'date': '2025-07-16', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 166, 'date': '2025-08-19', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 167, 'date': '2025-05-10', 'time': '1', 'field': '2', 'home_team_score': 2, 'away_team_score': 7, 'played': True, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 168, 'date': '2025-06-13', 'time': '2', 'field': '1', 'home_team_score': 6, 'away_team_score': 7, 'played': True, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 169, 'date': '2025-08-08', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 170, 'date': '2025-06-07', 'time': '3', 'field': '2', 'home_team_score': 5, 'away_team_score': 1, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 171, 'date': '2025-07-02', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 172, 'date': '2025-06-28', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 173, 'date': '2025-08-20', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 174, 'date': '2025-07-10', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 175, 'date': '2025-06-27', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 176, 'date': '2025-05-23', 'time': '3', 'field': '3', 'home_team_score': 3, 'away_team_score': 3, 'played': True, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 177, 'date': '2025-07-17', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 178, 'date': '2025-06-24', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 179, 'date': '2025-05-09', 'time': '1', 'field': '2', 'home_team_score': 6, 'away_team_score': 3, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 180, 'date': '2025-05-07', 'time': '2', 'field': '3', 'home_team_score': 7, 'away_team_score': 7, 'played': True, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 181, 'date': '2025-08-05', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 182, 'date': '2025-05-06', 'time': '3', 'field': '2', 'home_team_score': 5, 'away_team_score': 3, 'played': True, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 183, 'date': '2025-07-18', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 184, 'date': '2025-06-12', 'time': '1', 'field': '1', 'home_team_score': 8, 'away_team_score': 5, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 185, 'date': '2025-05-20', 'time': '3', 'field': '2', 'home_team_score': 3, 'away_team_score': 5, 'played': True, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 186, 'date': '2025-07-11', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 187, 'date': '2025-05-23', 'time': '3', 'field': '1', 'home_team_score': 8, 'away_team_score': 1, 'played': True, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 188, 'date': '2025-05-29', 'time': '1', 'field': '3', 'home_team_score': 1, 'away_team_score': 1, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 189, 'date': '2025-05-31', 'time': '1', 'field': '2', 'home_team_score': 1, 'away_team_score': 2, 'played': True, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 190, 'date': '2025-06-06', 'time': '3', 'field': '1', 'home_team_score': 3, 'away_team_score': 3, 'played': True, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 191, 'date': '2025-07-05', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 192, 'date': '2025-07-09', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 193, 'date': '2025-07-12', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 194, 'date': '2025-08-01', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 195, 'date': '2025-06-18', 'time': '1', 'field': '1', 'home_team_score': 7, 'away_team_score': 6, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 196, 'date': '2025-05-30', 'time': '1', 'field': '3', 'home_team_score': 3, 'away_team_score': 1, 'played': True, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 197, 'date': '2025-06-26', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 198, 'date': '2025-05-14', 'time': '3', 'field': '1', 'home_team_score': 3, 'away_team_score': 8, 'played': True, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 199, 'date': '2025-05-10', 'time': '3', 'field': '1', 'home_team_score': 4, 'away_team_score': 1, 'played': True, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 200, 'date': '2025-08-08', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 201, 'date': '2025-06-25', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 202, 'date': '2025-07-31', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 203, 'date': '2025-07-29', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 204, 'date': '2025-05-06', 'time': '2', 'field': '2', 'home_team_score': 4, 'away_team_score': 4, 'played': True, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 205, 'date': '2025-07-03', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 206, 'date': '2025-05-28', 'time': '1', 'field': '2', 'home_team_score': 2, 'away_team_score': 8, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 207, 'date': '2025-07-23', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 208, 'date': '2025-07-25', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 209, 'date': '2025-05-28', 'time': '1', 'field': '1', 'home_team_score': 5, 'away_team_score': 7, 'played': True, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 210, 'date': '2025-08-15', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 211, 'date': '2025-08-09', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 212, 'date': '2025-08-07', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 18, 'home_team_name': 'Nationals', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 213, 'date': '2025-06-06', 'time': '2', 'field': '1', 'home_team_score': 1, 'away_team_score': 8, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 20, 'away_team_name': 'Marlins'}, 
        {'id': 214, 'date': '2025-07-03', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 215, 'date': '2025-06-11', 'time': '1', 'field': '2', 'home_team_score': 4, 'away_team_score': 6, 'played': True, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 216, 'date': '2025-05-27', 'time': '2', 'field': '1', 'home_team_score': 8, 'away_team_score': 3, 'played': True, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 217, 'date': '2025-07-08', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 218, 'date': '2025-05-16', 'time': '3', 'field': '3', 'home_team_score': 5, 'away_team_score': 4, 'played': True, 'home_team_id': 16, 'home_team_name': 'Giants', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 219, 'date': '2025-05-22', 'time': '2', 'field': '1', 'home_team_score': 1, 'away_team_score': 2, 'played': True, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 220, 'date': '2025-07-05', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 15, 'away_team_name': 'Braves'}, 
        {'id': 221, 'date': '2025-08-19', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 19, 'home_team_name': 'Rays', 'away_team_id': 21, 'away_team_name': 'Yankees'}, 
        {'id': 222, 'date': '2025-07-24', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 17, 'home_team_name': 'Brewers', 'away_team_id': 16, 'away_team_name': 'Giants'}, 
        {'id': 223, 'date': '2025-08-07', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 15, 'home_team_name': 'Braves', 'away_team_id': 19, 'away_team_name': 'Rays'}, 
        {'id': 224, 'date': '2025-07-30', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 20, 'home_team_name': 'Marlins', 'away_team_id': 18, 'away_team_name': 'Nationals'}, 
        {'id': 225, 'date': '2025-05-08', 'time': '2', 'field': '1', 'home_team_score': 5, 'away_team_score': 4, 'played': True, 'home_team_id': 21, 'home_team_name': 'Yankees', 'away_team_id': 17, 'away_team_name': 'Brewers'}, 
        {'id': 226, 'date': '2025-06-03', 'time': '3', 'field': '1', 'home_team_score': 2, 'away_team_score': 2, 'played': True, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 227, 'date': '2025-06-17', 'time': '1', 'field': '1', 'home_team_score': 7, 'away_team_score': 8, 'played': True, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 228, 'date': '2025-06-05', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 2, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 229, 'date': '2025-08-19', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 230, 'date': '2025-07-17', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 231, 'date': '2025-05-16', 'time': '3', 'field': '2', 'home_team_score': 4, 'away_team_score': 5, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 232, 'date': '2025-08-15', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 233, 'date': '2025-08-12', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 234, 'date': '2025-07-10', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 235, 'date': '2025-08-16', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 236, 'date': '2025-06-04', 'time': '2', 'field': '2', 'home_team_score': 1, 'away_team_score': 3, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 237, 'date': '2025-07-24', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 238, 'date': '2025-08-08', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 239, 'date': '2025-05-09', 'time': '2', 'field': '3', 'home_team_score': 6, 'away_team_score': 2, 'played': True, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 240, 'date': '2025-06-25', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 241, 'date': '2025-05-07', 'time': '2', 'field': '1', 'home_team_score': 4, 'away_team_score': 3, 'played': True, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 242, 'date': '2025-08-07', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 243, 'date': '2025-06-14', 'time': '3', 'field': '2', 'home_team_score': 4, 'away_team_score': 2, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 244, 'date': '2025-07-08', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 245, 'date': '2025-08-09', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 246, 'date': '2025-06-28', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 247, 'date': '2025-07-31', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 248, 'date': '2025-06-27', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 249, 'date': '2025-08-15', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 250, 'date': '2025-07-15', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 251, 'date': '2025-07-26', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 252, 'date': '2025-05-23', 'time': '3', 'field': '2', 'home_team_score': 4, 'away_team_score': 3, 'played': True, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 253, 'date': '2025-06-21', 'time': '1', 'field': '3', 'home_team_score': 6, 'away_team_score': 2, 'played': True, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 254, 'date': '2025-07-19', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 255, 'date': '2025-08-14', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 256, 'date': '2025-05-20', 'time': '2', 'field': '1', 'home_team_score': 6, 'away_team_score': 2, 'played': True, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 257, 'date': '2025-07-23', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 258, 'date': '2025-05-20', 'time': '1', 'field': '3', 'home_team_score': 1, 'away_team_score': 3, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 259, 'date': '2025-06-11', 'time': '2', 'field': '3', 'home_team_score': 7, 'away_team_score': 5, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 260, 'date': '2025-07-22', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 261, 'date': '2025-05-20', 'time': '1', 'field': '2', 'home_team_score': 1, 'away_team_score': 3, 'played': True, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 262, 'date': '2025-07-09', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 263, 'date': '2025-05-07', 'time': '3', 'field': '2', 'home_team_score': 2, 'away_team_score': 6, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 264, 'date': '2025-07-26', 'time': '2', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 265, 'date': '2025-06-18', 'time': '3', 'field': '3', 'home_team_score': 7, 'away_team_score': 1, 'played': True, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 266, 'date': '2025-05-15', 'time': '3', 'field': '1', 'home_team_score': 7, 'away_team_score': 2, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 267, 'date': '2025-06-03', 'time': '1', 'field': '3', 'home_team_score': 7, 'away_team_score': 8, 'played': True, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 268, 'date': '2025-07-29', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 269, 'date': '2025-08-06', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 270, 'date': '2025-06-19', 'time': '1', 'field': '1', 'home_team_score': 4, 'away_team_score': 5, 'played': True, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 271, 'date': '2025-06-07', 'time': '1', 'field': '2', 'home_team_score': 4, 'away_team_score': 8, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 272, 'date': '2025-08-19', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 273, 'date': '2025-07-16', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 274, 'date': '2025-07-16', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 275, 'date': '2025-05-27', 'time': '2', 'field': '3', 'home_team_score': 4, 'away_team_score': 8, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 276, 'date': '2025-05-14', 'time': '2', 'field': '1', 'home_team_score': 3, 'away_team_score': 1, 'played': True, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 277, 'date': '2025-06-27', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 278, 'date': '2025-07-11', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 279, 'date': '2025-06-26', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 280, 'date': '2025-07-18', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 281, 'date': '2025-05-08', 'time': '3', 'field': '2', 'home_team_score': 5, 'away_team_score': 3, 'played': True, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 282, 'date': '2025-08-12', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 283, 'date': '2025-07-04', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 284, 'date': '2025-08-16', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 285, 'date': '2025-05-17', 'time': '1', 'field': '3', 'home_team_score': 4, 'away_team_score': 7, 'played': True, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 286, 'date': '2025-06-24', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 287, 'date': '2025-08-02', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 25, 'home_team_name': 'Reds', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 288, 'date': '2025-08-01', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 27, 'away_team_name': 'Pirates'}, 
        {'id': 289, 'date': '2025-07-12', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 290, 'date': '2025-05-21', 'time': '1', 'field': '1', 'home_team_score': 5, 'away_team_score': 5, 'played': True, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 24, 'away_team_name': 'Mets'}, 
        {'id': 291, 'date': '2025-07-12', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 292, 'date': '2025-06-25', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 293, 'date': '2025-05-10', 'time': '3', 'field': '3', 'home_team_score': 3, 'away_team_score': 1, 'played': True, 'home_team_id': 23, 'home_team_name': 'Diamondbacks', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 294, 'date': '2025-05-22', 'time': '1', 'field': '1', 'home_team_score': 5, 'away_team_score': 4, 'played': True, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 295, 'date': '2025-05-31', 'time': '3', 'field': '2', 'home_team_score': 7, 'away_team_score': 7, 'played': True, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 22, 'away_team_name': 'Red Sox'}, 
        {'id': 296, 'date': '2025-06-21', 'time': '2', 'field': '3', 'home_team_score': 1, 'away_team_score': 1, 'played': True, 'home_team_id': 26, 'home_team_name': 'Phillies', 'away_team_id': 28, 'away_team_name': 'Mariners'}, 
        {'id': 297, 'date': '2025-06-12', 'time': '2', 'field': '3', 'home_team_score': 8, 'away_team_score': 7, 'played': True, 'home_team_id': 24, 'home_team_name': 'Mets', 'away_team_id': 23, 'away_team_name': 'Diamondbacks'}, 
        {'id': 298, 'date': '2025-06-17', 'time': '3', 'field': '1', 'home_team_score': 3, 'away_team_score': 2, 'played': True, 'home_team_id': 22, 'home_team_name': 'Red Sox', 'away_team_id': 26, 'away_team_name': 'Phillies'}, 
        {'id': 299, 'date': '2025-07-05', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 27, 'home_team_name': 'Pirates', 'away_team_id': 25, 'away_team_name': 'Reds'}, 
        {'id': 300, 'date': '2025-08-05', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 28, 'home_team_name': 'Mariners', 'away_team_id': 24, 'away_team_name': 'Mets'}
    ]
    assert(response == games)

@pytest.mark.asyncio
async def test_team_games():
    response = await team_games(TeamID(team_id=1))
    games = [
        {'id': 4, 'date': '2025-06-13', 'time': '2', 'field': '3', 'home_team_score': 7, 'away_team_score': 4, 'played': True, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 7, 'date': '2025-05-23', 'time': '1', 'field': '1', 'home_team_score': 8, 'away_team_score': 4, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 10, 'date': '2025-08-09', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 13, 'date': '2025-08-06', 'time': '3', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 16, 'date': '2025-08-15', 'time': '2', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 19, 'date': '2025-07-02', 'time': '3', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 25, 'date': '2025-05-21', 'time': '1', 'field': '2', 'home_team_score': 8, 'away_team_score': 4, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 28, 'date': '2025-05-31', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 1, 'played': True, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 31, 'date': '2025-05-22', 'time': '3', 'field': '1', 'home_team_score': 6, 'away_team_score': 8, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 5, 'away_team_name': 'Dodgers'}, 
        {'id': 34, 'date': '2025-08-02', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 4, 'home_team_name': 'Jays', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 37, 'date': '2025-08-20', 'time': '2', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 3, 'away_team_name': 'Orioles'}, 
        {'id': 40, 'date': '2025-08-08', 'time': '1', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 2, 'home_team_name': 'Cardinals', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 46, 'date': '2025-06-28', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 7, 'home_team_name': 'Astros', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 49, 'date': '2025-07-17', 'time': '1', 'field': '3', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 6, 'away_team_name': 'Rangers'}, 
        {'id': 52, 'date': '2025-05-08', 'time': '1', 'field': '2', 'home_team_score': 6, 'away_team_score': 3, 'played': True, 'home_team_id': 5, 'home_team_name': 'Dodgers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 55, 'date': '2025-07-23', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 4, 'away_team_name': 'Jays'}, 
        {'id': 58, 'date': '2025-08-14', 'time': '1', 'field': '1', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 3, 'home_team_name': 'Orioles', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 61, 'date': '2025-06-04', 'time': '2', 'field': '3', 'home_team_score': 4, 'away_team_score': 3, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 2, 'away_team_name': 'Cardinals'}, 
        {'id': 67, 'date': '2025-08-13', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 7, 'away_team_name': 'Astros'}, 
        {'id': 70, 'date': '2025-08-16', 'time': '3', 'field': '2', 'home_team_score': 0, 'away_team_score': 0, 'played': False, 'home_team_id': 6, 'home_team_name': 'Rangers', 'away_team_id': 1, 'away_team_name': 'Tigers'}, 
        {'id': 73, 'date': '2025-05-07', 'time': '1', 'field': '3', 'home_team_score': 5, 'away_team_score': 2, 'played': True, 'home_team_id': 1, 'home_team_name': 'Tigers', 'away_team_id': 5, 'away_team_name': 'Dodgers'}
    ]
    assert(response == games)

@pytest.mark.asyncio
async def test_create_RR():
    response = await create_RR(
        RescheduleRequest(
            requester_id=1, 
            receiver_id=2, 
            game_id=19, 
            option1="this is a test RR", 
            option2=None, 
            option3=None, 
            option4=None, 
            option5=None, 
            option1_field="1",
            option2_field=None,
            option3_field=None,
            option4_field=None,
            option5_field=None,
        )
    )
    assert(response == "reschedule request created")

RRid = None

@pytest.mark.asyncio
async def test_get_team_RRs():
    response = await get_team_RRs(TeamID(team_id=2))
    global RRid 
    RRid = response[0]['id']
    RR = [
        {'id': RRid, 'game_id': 19, 'option1': 'this is a test RR', 'option1_field': '1', 'option2': None, 'option2_field': None, 'option3': None, 'option3_field': None, 'option4': None, 'option4_field': None, 'option5': None, 'option5_field': None, 'requester_id': 1, 'requester_team_name': 'Tigers', 'reciever_id': 2, 'reciever_team_name': 'Cardinals', 'date': '2025-07-02', 'time': '3', 'field': '3'}
    ]
    assert(response == RR)

@pytest.mark.asyncio
async def test_delete_reschedule_request():
    global RRid
    response = delete_reschedule_request(RRid)
    assert(response == "reschedule request deleted")