# This workflow will install Python dependencies, run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt
    - name: List python packages
      run: |
        python -m pip list
    - name: Test with pytest
      run: |
        pytest --html=tests/Reports/Report.html
    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Pytest Report           # Name of the folder
        path: tests/Reports           # Path to test results
